# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessTokens',
            new_name='AccessToken',
        ),
    ]
